@startuml
left to right direction
skinparam card {
    roundCorner 8
}

'Cards ---
'Primitive MEtals
card Atlarus
card Adamantine
card "**Copper**" as Copper
card "**Deep Iron**" as DeepIron
card "**Prometheum**" as Prometheum
card Osmium
card Silver
card Infuscolium
card Manganese
card "Astral Silver" as AstralSilver
card "**Ignatius**" as Ignatius
card Oureclase
card Rubracium
card "**Shadow Iron**" as ShadowIron
card Ceruclase
card "**Eximite**" as Eximite
card Kalendrite
card Midasium
card Orichalcum
card Platinum
card "**Vulcanite**" as Vulcanite
card Alduorite
card Carmot
card Lemurite
card Lutetium
card Meutoite
card Mithril
card Sanguinite
card Vyroxeres
card Tin
card Zinc


'Alloys
card "Angmallen\n(Iron + Gold)" as Angmallen
card "**Steel**\n(Iron + Manganese)" as Steel
card "**Black Steel**\n(Deep Iron + Infuscolium)" as BlackSteel
card "Electrum\n(Silver + Gold)" as Electrum
card "**Hepatizon**\n(Steel + Infuscolium)" as Hepatizon
card "**Bronze**\n(Tin + Copper)" as Bronze
card "**Brass**\n(Zinc + Copper)" as Brass
card "**Damascus Steel**\n(Bronze + Iron)" as DamascusSteel
card "Quicksilver\n(Astral Silver + Silver)" as Quicksilver
card "**Celenegil**\n(Orichalcum + Platinum)" as Celenegil
card "Amordrine\n(Kalendrite + Platinum)" as Amordrine
card "**Shadow Steel**\n(Shadow Iron + Lemurite)" as ShadowSteel
card "Inolashite\n(Ceruclase + Alduorite)" as Inolashite
card "**Haderoth**\n(Mithril + Rubracium)" as Haderoth
card "**Desichalkos**\n(Eximite + Meutoite)" as Desichalkos
card "Krik\n(Osmium + Lutetium)" as Krik
card "**Tartarite**\n(Adamantine + Atlarus)" as Tartarite
card "Etherium\n(Sanguinite + Alduorite)" as Etherium


'Tiers
node root [
    Start | Tier 1
    ....
    root achievement
]
node tier2 [
    Tier 2
]
node tier3 [
    Tier 3
]
node tier4 [
    Tier 4
]
node tier5 [
    Tier 5
]
node tier6 [
    Tier 6
]


'Tier 1 achievements [Parent is root]
root-->Copper
root-->DeepIron
root-->Prometheum
root-->Tin
root-->Zinc
root-->Bronze
root-->Brass
Bronze-->DamascusSteel
root-->tier2

'Tier 2 achievements
tier2-->Angmallen
tier2-->Osmium
tier2-->Silver
tier2-->Infuscolium
tier2-->Manganese
tier2-->Steel
tier2-->BlackSteel
tier2-->Electrum
Steel-->Hepatizon
tier2-->tier3

'Tier 3 Achievements
tier3-->AstralSilver
tier3-->Ignatius
tier3-->Oureclase
tier3-->Rubracium
tier3-->ShadowIron
tier3-->Quicksilver
tier3-->tier4

'Tier 4 Achievements
tier4-->Ceruclase
tier4-->Eximite
tier4-->Kalendrite
tier4-->Midasium
tier4-->Orichalcum
tier4-->Platinum
tier4-->Vulcanite
tier4-->Celenegil
tier4-->Amordrine
tier4-->tier5

'Tier 5 Achievemets
tier5-->Carmot
tier5-->Lemurite
tier5-->Meutoite
tier5-->Mithril
tier5-->Sanguinite
tier5-->Vyroxeres
tier5-->ShadowSteel
tier5-->Haderoth
tier5-->Desichalkos
tier5-->tier6

'Tier 6 Achievements
tier6-->Alduorite
tier6-->Atlarus
tier6-->Adamantine
tier6-->Lutetium
tier6-->Tartarite
tier6-->Etherium
tier6-->Inolashite
tier6-->Krik

@enduml


